const { Schema, model } = require("mongoose");

const formSchema = new Schema(
  {
    type: { type: String, required: false },
    orgName: { type: String, required: false },
    taxId: { type: String, required: false },
    addressOne: { type: String, required: false },
    addressTwo: { type: String, required: false },
    city: { type: String, required: false },
    state: { type: String, required: false },
    postalCode: { type: String, required: false },
    workPhone: { type: String, required: false },
    email: { type: String, required: false },
    webSite: { type: String, required: false },
    firstName: { type: String, required: false },
    lastName: { type: String, required: false },
    title: { type: String, required: false },
    personalWorkPhone: { type: String, required: false },
    personalEmail: { type: String, required: false },
    dayShelter: { type: Boolean, required: false },
    overnightShelter: { type: Boolean, required: false },
    safeHaven: { type: Boolean, required: false },
    safeHavenDescription: { type: String, required: false },
    maternityPrograms: { type: Boolean, required: false },
    youthShelters: { type: Boolean, required: false },
    domesticViolenceShelters: { type: Boolean, required: false },
    flexShelters: { type: Boolean, required: false },
    hybridTransitionalShelters: { type: Boolean, required: false },
    programsExperiencingHomelessness: { type: Boolean, required: false },
    genderBasedViolencePrograms: { type: Boolean, required: false },
    other: { type: Boolean, required: false },
    otherDescription: { type: String, required: false },
    scope: { type: Boolean, required: false },
    scopeDescription: { type: String, required: false },
    fees: { type: Boolean, required: false },
    feesDescription: { type: String, required: false },
    pay: { type: Boolean, required: false },
    howManyLocations: { type: String, required: false },
    howManyShelters: { type: String, required: false },
    howManyBedNights: { type: String, required: false },
    units: { type: String, required: false },
    meals: { type: String, required: false },
    counseling: { type: String, required: false },
    types: { type: String, required: false },
    women: { type: String, required: false },
    children: { type: String, required: false },
    association: { type: Boolean, required: false },
    mission: { type: String, required: false },
    becomeMembers: { type: String, required: false },
    sheltering: { type: Boolean, required: false },
    howManyMembers: { type: String, required: false },
    name: { type: String, required: false },
    additionalInfo: { type: String, required: false },
    interest: { type: String, required: false },
    skills: { type: String, required: false },
    computer: { type: Boolean, required: false },
    time: { type: String, required: false },
    remote: { type: Boolean, required: false },
    travel: { type: Boolean, required: false },
    add: { type: String, required: false },
    source: { type: String, required: false },
    pending:{ type: Boolean}
  },
  {
    timestamps: true,
  }
);

module.exports = model("Form", formSchema);